### ISSUE TITLE
Compatibility Issue: NumPy 2.0+ Causes Errors in Triton Interpret Mode

### ISSUE THREAD

**Issue by justcyl** [SiriusNEO/Triton-Puzzles-Lite#1]
**Description**:  
Running Triton in interpret mode (`TRITON_INTERPRET=1`) with NumPy 2.0 or higher can lead to unexpected errors. Downgrading NumPy to a version below 2.0 (e.g., 1.21.x or 1.22.x) resolves these issues.

**Steps to Fix**:
1. Check your NumPy version:
   ```bash
   pip show numpy
   ```
2. If `numpy >= 2.0`, downgrade with:
   ```bash
   pip install numpy<2.0
   ```

**Comment by SiriusNEO** [comment]
I use `numpy==2.1.2` and don't meet errors. It may be the version. It may also have something to do with the version of torch and triton.
